// 符文机枢 UI 材质包 · OpenAI 图像管线(圣经 §7.5 三分法)
// 用法: node tools/gen-assets.mjs [--only 名称片段] [--force]
import fs from 'fs'; import path from 'path';
const ROOT = new URL('..', import.meta.url).pathname;
const KEY = fs.readFileSync(path.join(ROOT,'.env'),'utf8').match(/OPENAI_API_KEY=(\S+)/)[1];
const OUT = path.join(ROOT,'prototypes/single-engine/art');
fs.mkdirSync(OUT,{recursive:true});

const FRAME = 'dark etched gunmetal game UI, hextech arcane style, engraved rune line ornaments, beveled machined edges, subtle cyan energy seams, symmetrical, clean silhouette, isolated on transparent background, no text';
const ENAMEL = 'polished enamel and gem game UI element, saturated inlay, soft specular highlight, matte dark metal socket, premium mobile game style, clean silhouette, centered, isolated on transparent background, no text';
const PAINT = 'hand-painted game illustration, visible painterly brushstrokes, rich texture, warm rim light against deep blue darkness, no text';

const ASSETS = [
 {f:'jb2-foe-sigma.png', s:'1024x1024', q:'high', bg:'transparent', p:`imposing stone door-god examiner general, mobile game boss illustration, 4.5 heads tall powerful proportion with broad massive shoulders, NOT chibi, fierce Peking-opera mask face paint dominated by cyan-blue and white with thin ink accents, huge glaring pupils with cold cyan glow, heavy stone brow pressed low, carved stone beard, ornate bronze taotie shoulder armor with restrained gold trim, glowing cyan seal-script sigma emblem centered on chest plate, arms crossed clutching a rolled exam scroll, stern unimpressed chief-examiner presence, warm ivory-grey stone body saturation under 30 percent, saturated cyan accents only, thick uniform dark ink-navy outlines #1E2430 4px outer 2px inner, flat two-tone cel shading, subtle xuan-paper grain, flat even daylight, symmetrical front view, isolated character on transparent background, NO chibi, NO cute round body, NO gradients, NO plastic highlights, NO dark background, NO horror, NO skulls, NO religious icons, NO red-dominant face`},
 {f:'jb2-foe-omega.png', s:'1024x1024', q:'high', bg:'transparent', p:`fierce night-prowler hunter examiner, mobile game boss illustration, 4.5 heads tall lean angular proportion, NOT chibi, wiry predator frame leaning sharply forward in coiled stalking pose, Chinese opera martial-clown face paint dominated by purple and white in narrow inverted-triangle layout, slit pupils with purple glow, sly cruel taunting smirk, dark ink-grey assassin robes with purple sash and wrapped forearms, glowing purple seal-script omega stamp on chest, asymmetric dynamic silhouette, warm ivory-grey base saturation under 30 percent, saturated purple accents only, thick uniform dark ink-navy outlines #1E2430 4px outer 2px inner, flat two-tone cel shading, subtle xuan-paper grain, flat even daylight, isolated character on transparent background, NO chibi, NO cute, NO weapons, NO gradients, NO dark background, NO horror, NO skulls, NO religious icons`},
 {f:'jb2-foe-delta.png', s:'1024x1024', q:'high', bg:'transparent', p:`colossal overlord general examiner, mobile game final boss illustration, 5 heads tall widest and bulkiest proportion, NOT chibi, Peking-opera wusheng warrior face paint dominated by orange-gold in wide upright-triangle layout, blazing flame-shaped eyebrows, furious burning glare, massive layered pauldrons and heavy chest armor, glowing orange-gold seal-script delta sigil on chest, arms-akimbo domineering stance, warm ivory-grey stone armor saturation under 30 percent with deep ink accents, saturated orange-gold reserved for face paint and sigil, thick uniform dark ink-navy outlines #1E2430 4px outer 2px inner, flat two-tone cel shading, subtle xuan-paper grain, flat even daylight, symmetrical imposing front view, isolated character on transparent background, NO chibi, NO cute, NO red-dominant face, NO gradients, NO dark background, NO horror, NO skulls, NO religious icons`},
 {f:'jb-avatar-you.png', s:'1024x1024', q:'medium', bg:'transparent', p:`chibi young scholar student avatar portrait, head and shoulders only, blue headband with small gold seal ornament, black topknot hair, big determined eyes, confident grin, blue scholar robe collar, thick dark ink-navy outlines #1E2430, flat two-tone cel shading, warm palette, mobile game avatar icon style, centered, isolated on transparent background, NO text, NO dark background, NO gradients`},
 {f:'jb-yamen-gate1.jpg', s:'1536x1024', q:'high', bg:'opaque', p:`mobile quiz battle arena background, landscape 1536x1024, full-bleed opaque scene, bright Chinese yamen courtroom arena inspired by imperial examination hall, warm rice-paper ivory ground, symmetrical composition: carved wooden paifang archway gate in soft-focus background center-top with a blank horizontal plaque, ceremonial hall columns flanking far left and right, distant scholar audience in muted blue-grey robes softly blurred, small cyan-blue vertical banners as only accent color, wide vacant central floor completely clean and empty for character and UI overlay, flat two-tone cel shading, uniform dark ink-navy #1E2430 outlines, subtle xuan-paper grain, flat even daylight, dignified exam-hall tension, NO text on plaque, NO legible characters, NO red-gold flooding, NO lanterns, NO darkness, NO characters in center, NO clutter in center`},
 {f:'jb-yamen-gate2.jpg', s:'1536x1024', q:'high', bg:'opaque', p:`mobile quiz battle arena background, landscape 1536x1024, full-bleed opaque scene, second-gate dusk variation of the same bright Chinese yamen examination-hall arena from gate one, identical symmetrical composition with carved paifang archway and columns, warm amber evening color temperature yet fully lit high-key, muted plum-purple vertical banners as only accent color, wide vacant central floor clean and empty for UI overlay, flat two-tone cel shading, uniform dark ink-navy #1E2430 outlines, subtle xuan-paper grain, flat even warm light, NO text, NO legible characters, NO red-gold flooding, NO darkness, NO characters, NO clutter in center`},
 {f:'jb-yamen-gate3.jpg', s:'1536x1024', q:'high', bg:'opaque', p:`mobile quiz battle arena background, landscape 1536x1024, full-bleed opaque scene, championship-final variation of the same bright Chinese yamen examination-hall arena from gates one and two, identical symmetrical paifang archway composition dressed for the final: thin matte gold trim lines tracing beam and plaque edges only covering under one tenth of scene, muted orange-gold vertical banners in mirror symmetry, confetti-free, wide vacant central floor clean and empty for UI overlay, warm rice-paper ivory base, flat two-tone cel shading, uniform dark ink-navy #1E2430 outlines, subtle xuan-paper grain, flat even daylight, festive scholarly final dignity, NO text, NO legible characters, NO overall red-gold scheme, NO darkness, NO characters, NO clutter in center`},
 {f:'jb-ui-console.png', s:'1536x1024', q:'high', bg:'transparent', p:`ornate rectangular frame border for a quiz console panel, Chinese xuan rice-paper scroll aesthetic, warm ivory paper border with aged fiber grain, crisp ink-navy #1E2430 double border lines 4px outer 2px inner, thin matte gold meander-pattern corner accents at four corners only covering under ten percent, completely empty transparent center for nine-slice scaling, flat two-tone cel shading, flat even daylight, symmetrical, clean silhouette, no text, NO dark gunmetal, NO glow effects, NO gradients, NO plastic highlights`},
 {f:'jb-ui-cardbg-silver.png', s:'1024x1536', q:'medium', bg:'opaque', p:`blank game card background, portrait, plain warm ivory xuan rice-paper card face with subtle fiber grain texture, single thin ink-navy #1E2430 rectangular inner frame line, tiny muted ink seal stamp accent at bottom right corner, flat two-tone cel shading, flat even daylight, quiet and clean, NO text, NO characters, NO gradients, NO darkness, NO gold, NO ornament clutter`},
 {f:'jb-ui-cardbg-gold.png', s:'1024x1536', q:'medium', bg:'opaque', p:`blank game card background, portrait, warm ivory xuan rice-paper card face with subtle fiber grain, double matte gold rectangular frame lines with small auspicious cloud line flourishes at corners only, thin ink-navy #1E2430 outer edge line, festive but restrained, flat two-tone cel shading, flat even daylight, NO text, NO characters, NO gradients, NO darkness, NO gold flooding, NO ornament clutter in center`},
 {f:'jb-ui-cardbg-prism.png', s:'1024x1536', q:'medium', bg:'opaque', p:`blank game card background, portrait, warm ivory xuan rice-paper card face with subtle fiber grain, iridescent glazed porcelain border frame shifting teal-purple-gold like liuli glass, thin ink-navy #1E2430 edge lines, mystical premium feel yet bright, flat two-tone cel shading, flat even daylight, NO text, NO characters, NO darkness, NO center ornament, NO neon`},
 {f:'jb-ui-drafttable.jpg', s:'1536x1024', q:'medium', bg:'opaque', p:`top-down view of a Chinese scholar study desk surface, warm ivory rice-paper desk mat covering most of frame, ink stone brush rest and small seal arranged sparsely along top edge, soft even warm daylight, muted low-saturation palette, large clean empty center area for card overlay, subtle wood grain at extreme edges, flat two-tone cel shading, calm scholarly mood, NO text, NO characters, NO darkness, NO clutter in center`},
 {f:'jb-foe-sigma.png', s:'1024x1024', q:'high', bg:'transparent', p:`isolated game boss character sprite, transparent background, symmetrical strict front view, chibi stone door-god examiner guardian general in Chinese guochao style, 3.5 heads tall squared-yet-rounded silhouette with crisp angular edges, Q-proportion imposing presence, Peking-opera face paint with cyan-blue as the dominant mask color, maximum three face-paint color zones, huge stern eyes spanning 40 percent of face width with cold cyan glow, single flat stone brow pressed low, unimpressed cold proctor expression, arms crossed over bronze taotie chest armor while clutching a rolled exam scroll, chest plate centered with a glowing cyan seal-script sigma sigil, muted stone-grey and ink-navy body on warm rice-paper ivory-grey base palette saturation under 30 percent at mid brightness, saturated cyan accents only, flat two-tone cel shading with cool-shifted shadow tone, uniform dark ink-navy outlines #1E2430 3-4px outer 1-2px inner, subtle xuan-paper grain texture, flat even daylight, NO gradients, NO plastic highlights, NO dark backgrounds, NO background scenery, NO horror, NO skulls, NO religious icons, NO calligraphy banners`},
 {f:'jb-foe-omega.png', s:'1024x1024', q:'high', bg:'transparent', p:`chibi Chinese guochao boss character concept, gatekeeper examiner Omega the hunter proctor, single isolated full-body character on transparent background, about 3 heads tall with lean angular faceted silhouette, wiry frame thinner and more slanted than a bulky door-god, leaning sharply forward in a perched gargoyle-like hunter crouch, Chinese opera martial-clown face-paint with purple as dominant color, narrow inverted-triangle patch layout, at most 3 flat color zones on the face, oversized eyes spanning 40% of face width with vertical slit pupils and purple iris anchor, sly taunting mischievous smirk, night-prowler swordsman attire in muted ink-grey cloth with purple sash and wrapped sleeves, glowing purple seal-script Omega stamp emblem on chest, warm rice-paper ivory-grey base palette saturation under 30% mid brightness, flat two-tone cel shading, uniform dark ink-navy outlines #1E2430 3-4px outer 1-2px inner, subtle xuan-paper grain texture, flat even daylight, NO gradients, NO plastic highlights, NO dark backgrounds, NO horror, NO religious icons, NO gold armor`},
 {f:'jb-foe-delta.png', s:'1024x1024', q:'high', bg:'transparent', p:`chibi door-god examiner boss character, mobile quiz battle game asset, 3.5 heads tall Q-proportion matching the Sigma guardian of the same trio, isolated on transparent background, imposing overlord-general Peking-opera wusheng warrior face paint in dominant orange-gold, wide upright-triangle face-paint silhouette, maximum three color zones, eyes over 40% of face width, blazing orange-gold flame-shaped eyebrows, furious burning glare, arms-akimbo domineering proctor stance, glowing orange-gold seal-script Delta sigil on chest plate, massive heavy layered pauldrons, bulkiest and widest silhouette of the trio, muted armor in warm rice-paper ivory-grey base (saturation ≤30%, mid brightness) with deep ink accents, saturated orange-gold reserved for face paint and chest sigil only, flat two-tone cel shading, uniform dark ink-navy outlines (#1E2430) 3-4px outer 1-2px inner, subtle xuan-paper grain texture, flat even daylight, clean bold silhouette readable at 100px, NO gradients, NO plastic highlights, NO dark backgrounds, NO background scenery, NO horror, NO religious icons, NO red-dominant face paint, NO casino imagery`},
 {f:'jb-bg-gate1.jpg', s:'1536x1024', q:'high', bg:'opaque', p:`mobile quiz battle game arena background, landscape 1536x1024, full-bleed opaque scene, wide symmetrical composition, empty variety-show esports stage on warm rice-paper ivory-grey base, saturation ≤30%, mid brightness, wide vacant central stage floor kept completely clean and empty for character and UI overlay, low broad platform with simple geometric edge trim, distant tiered audience seating softly blurred and desaturated behind, a few small muted cyan-blue vertical banners flanking left and right in mirror symmetry as the only color accent, sparse quiet composition, calm competitive studio air with a faint scholarly exam-hall dignity, background stays visually recessive so foreground elements dominate, flat two-tone cel shading, uniform dark ink-navy outlines #1E2430 3-4px outer 1-2px inner, subtle xuan-paper grain texture, flat even daylight, NO gradients, NO plastic highlights, NO dark backgrounds, NO horror, NO religious icons, NO red-gold decoration, NO lanterns, NO archway gates, NO ornament clutter, NO text, NO characters, NO UI elements, NO busy patterns in center`},
 {f:'jb-bg-gate2.jpg', s:'1536x1024', q:'high', bg:'opaque', p:`mobile quiz battle arena background, landscape 1536x1024, full-bleed opaque scene, second-round variation of the same bright variety-show esports studio stage, warm dusk color temperature yet still fully lit and high-key, warm rice-paper ivory-grey base shifted toward amber evening tones, saturation ≤30%, mid brightness, flat two-tone cel shading, uniform dark ink-navy #1E2430 outlines 3-4px outer 1-2px inner, subtle xuan-paper grain texture, flat even shadowless warm light, wide symmetrical composition matching round one, clean empty center stage floor and mid-air reserved for UI question card, plain unpatterned central area, muted plum-purple hanging banners flanking the stage as the only accent color, soft-focus simplified audience silhouettes in desaturated warm grey along the far edges, generic culturally-neutral modern studio rigging and screen panels, festive scholarly tournament mood, NO gradients, NO plastic highlights, NO dark backgrounds, NO red-gold decoration, NO ornate Chinese architecture, NO patterns or props in center, NO text, NO characters, NO horror, NO religious icons`},
 {f:'jb-bg-gate3.jpg', s:'1536x1024', q:'high', bg:'opaque', p:`mobile quiz battle arena background, landscape 1536x1024, full-bleed opaque scene, third-gate championship-final variation of the same bright variety-show esports studio stage from rounds one and two, wide symmetrical composition matching the previous rounds, warm rice-paper ivory-grey base, saturation ≤30%, mid brightness, the familiar culturally-neutral modern studio dressed up for the final: thin matte gold trim lines tracing only the existing stage framework edges and screen-panel borders, gold kept as sparse linework ornament covering well under one tenth of the scene and never flooding any surface, muted orange-gold festival flags and hanging pennants flanking left and right in mirror symmetry, blank banners without lettering, central stage floor and mid-air kept completely clean and empty for UI overlay, plain unpatterned central area, soft-focus simplified audience silhouettes in desaturated warm grey along the far edges, studio light truss high above rendered in low-saturation warm grey, flat two-tone cel shading, uniform dark ink-navy outlines #1E2430 3-4px outer 1-2px inner, subtle xuan-paper grain texture, flat even daylight, festive final-round atmosphere with quiet scholarly tournament dignity, NO ornate Chinese architecture, NO proscenium arch, NO carved wood pillars or roof beams, NO overall red-gold scheme, NO gradients, NO plastic highlights, NO dark backgrounds, NO characters, NO legible text, NO horror, NO religious icons, NO patterns or props in center`},
 {f:'jb-keyart.jpg', s:'1024x1536', q:'high', bg:'opaque', p:`heroic mobile quiz battle game key art splash, portrait 1024x1536 full-bleed, warm rice-paper ivory-grey base with saturation ≤30% and mid brightness, upper third left as clean negative space for logo, center focus: a giant calligraphy ink brush morphing into an upward-pointing sword, blade tip crowned by a small crisp flat cel-style golden halo shape, a grand imperial exam honor-roll scroll unfurling behind it rendered in warm ivory paper, matte gold trim on the scroll frame edges only while the scroll surface stays ivory, abstract vertical ink-stroke columns on the scroll with no legible characters, three carved seal-script stamp emblems circling the blade — cyan-blue Sigma seal, purple Omega seal, orange-gold Delta seal — rendered as flat stone chops, festive scholarly exam-day triumph, bold and blood-pumping not cute, flat two-tone cel shading, uniform dark ink-navy #1E2430 outlines 3-4px outer 1-2px inner, subtle xuan-paper grain texture, flat even daylight, NO gradients, NO plastic highlights, NO dark backgrounds, NO red-gold flooding, NO gold-flooded surfaces, NO horror, NO skulls, NO religious icons, NO casino imagery, NO legible text`},
 {f:'concept-v-jinbang-guochao.jpg', s:'1024x1536', q:'high', bg:'opaque', p:`mobile quiz battle game UI concept art, portrait 1024x1536, BRIGHT Chinese guochao variety-show esports arena on warm low-saturation rice-paper ivory stage, matte gold trim on panel frames only, strict 10-color palette, uniform dark ink-navy #1E2430 outlines 3-4px outer 1-2px inner on every element, flat two-tone cel shading with subtle xuan-paper grain, flat even daylight, festive scholarly exam-hall tension. Top: cyan-blue YOU versus red-orange RIVAL tug-of-war bar clashing at gold VS emblem. Upper-left below capsule: orange brush-stroke combo flame counter. Upper-center: red-orange health bar over chibi door-god examiner boss, 3 heads tall, three-zone opera face-paint, bronze taotie armor, crossed-arm proctor pose, stone brow, cyan eye glow. Center: crisp paper-white question card, single highest-contrast element, ink text, four saturated cyan-blue answer buttons in one column, slim incense-stick countdown, ember tip, above card. Left edge: muted-ink carved-seal build column. Bottom corners: square carved-seal skill tiles, cyan liquid-fill energy inside tiles. NO independent energy bar, NO rank-ladder motif, NO lower-area combo counter, NO darkness, NO patterns near question card, NO red-gold flooding, NO horror, NO skulls, NO religious icons, NO gradients, NO casino imagery`},
 {f:'concept-v-liangle-mainstream-bright.jpg', s:'1024x1536', q:'high', bg:'opaque', p:`mobile quiz battle game UI concept art, portrait 1024x1536, BRIGHT esports variety-show studio arena, low-saturation pale teal-grey stage, flat even daylight lighting, strict 10-color palette, saturation reserved for information layer only, uniform dark-navy outlines 3-4px outer 1-2px inner on every element, flat two-tone cel shading, felt-grain texture, top: red YOU versus blue RIVAL tug-of-war bar clashing at gold VS emblem, upper-center: stone golem examiner boss, 3 heads tall, chunky angular geometric silhouette, flat stone brow pressed low, arms crossed gazing down, glowing cyan sigma rune on chest, center: crisp ivory-white question card, single highest-contrast element, bold dark text, four full-width cyan-blue answer buttons in one column, left: tall orange combo flame capsule, right: countdown ring with red final-third arc, above skill row: horizontal strip of small greyscale rune badges showing equipped build, bottom corners: squared low-radius rune skill tiles including one wax-seal wager tile, blue energy liquid inside buttons, cheerful fierce game-show exam energy, NO dark background, NO horror, NO skulls, NO religious symbols, NO casino imagery, NO coins, NO gradients, NO neon-on-black, NO photorealism`},
 {f:'concept-v-nuanyang-mass-warm.jpg', s:'1024x1536', q:'high', bg:'opaque', p:`mobile quiz battle game UI concept art, portrait 1024x1536, bright warm mass-market casual arena in match-3 aesthetic, cream-apricot backdrop, single focal point, limited 10-color palette: warm cream base, paper white, deep ink-navy, bright sky cyan, combo orange, rival red-orange, rare gold accents, uniform dark-navy outlines 4px outer 2px inner, flat two-tone cel shading, zero gradients, flat even daylight, top chunky red versus blue tug-of-war bar with gold VS badge, upper-center warm sandstone golem examiner, 3 heads tall, huge friendly close-up face, eyes 40 percent of face width, one stern flat stone brow, cyan glint in eyes, holding a score paddle rimmed by a red-orange charge arc, center big pure-white question card as single highest-contrast element, giant bold dark text, four full-width candy-slab answer buttons in one column, thick outlines, small red-orange bet chip announcing next-question-doubles beside the card, lower orange flame combo counter, cyan energy bar, bottom corners compact square rune skill tiles, cheerful daytime game-show energy with real stakes, ad-ready first frame, NO darkness, NO horror, NO skulls, NO religious symbols, NO casino slot imagery, NO neon, NO pastel macaron, NO gradients, NO clutter`},
 {f:'concept-v-xideng-dark-finals.jpg', s:'1024x1536', q:'high', bg:'opaque', p:`mobile quiz battle game UI concept art, portrait 1024x1536, esports quiz studio, house lights off for finals night, deep desaturated slate-navy stage never pure black, dim cyan rune etchings on floor, one cool overhead spotlight cone, strict 11-color palette, one accent per channel: cyan energy, combo-only orange flame, red-orange rival danger, transient gold only, decoration pressed muted grey-navy, uniform dark navy outlines 3-4px outer 1-2px inner, flat two-tone cel shading, characters keep bright daylight colors, top: fully bright red YOU versus blue RIVAL tug-of-war bar with glowing VS emblem, upper-center: chibi stone golem examiner, 3 heads tall, chunky granite body, stern flat stone brow, glowing cyan sigma rune on chest, arms-crossed proctor pose, center: luminous ivory question card as the single highest-contrast element, extra-large bold dark navy question text, four saturated cyan answer buttons with thick outlines, lower: orange flame combo counter, cyan energy bar, red-orange crystal multiplier gems, blackout-final tension, fierce but clean, NO pure black, NO horror, NO skulls, NO occult or religious symbols, NO blue-purple haze, NO casino slot-machine imagery, NO muddy darkness`},
 {f:'concept-liangl-battle.jpg', s:'1024x1536', q:'high', bg:'opaque', p:`mobile quiz battle game UI concept art, portrait. BRIGHT competitive arena: light teal-grey stage (NOT dark), bold thick black outlines everywhere, flat two-tone cel shading, saturated warm colors on characters and buttons, limited 10-color palette. Top: chibi stone golem examiner boss, 2.5 heads tall, chunky geometric silhouette, glowing cyan sigma rune chest, smug intimidating proctor expression, red-versus-blue duel progress bar. Center: clean white question card highest contrast with bold dark text, four bright answer buttons thick outlines. Bottom: orange fire combo counter, blue energy bar, red-orange multiplier gems. Speed lines, confetti particles, esports variety-show stage energy. Style: Brawl Stars meets TFT mobile, cheerful but fierce, NO darkness NO horror`},
  {f:'concept-liangl-sigma.png', s:'1024x1024', q:'high', bg:'transparent', p:`chibi stone golem examiner boss character, 2.5 heads tall, chunky geometric rock body with sharp angular silhouette, glowing cyan sigma rune core on chest, thick bold black outer outlines with thinner inner lines, flat cel shading exactly two tones per color, saturated bright colors, smug intimidating expression like a strict exam proctor, arms crossed, cartoon exaggeration, Brawl Stars Clash Royale character style, isolated on transparent background, NO dark atmosphere`},
  {f:'foe-sigma.png', s:'1024x1024', q:'high', bg:'transparent', p:`ancient stone golem guardian, floating cracked rock torso with glowing cyan sigma rune core, slow heavy presence, orbiting stone fragments, cyan energy veins in cracks, symmetrical front view, isolated character on transparent background, ${PAINT}`},
  {f:'foe-omega.png', s:'1024x1024', q:'high', bg:'transparent', p:`spectral hunter wraith, sleek predator silhouette formed of violet smoke and blades, glowing purple omega rune as its eye, mid-lunge coiled posture, thin sharp shapes, asymmetric dynamic front view, isolated character on transparent background, ${PAINT}`},
  {f:'foe-delta.png', s:'1024x1024', q:'high', bg:'transparent', p:`tyrant overlord avatar, monolithic triangular obsidian crown-form wreathed in crimson flame, glowing red delta rune heart, ember particles rising, oppressive scale, throne-like silhouette, symmetrical imposing front view, isolated character on transparent background, ${PAINT}`},
  {f:'keyart-title.jpg', s:'1536x1024', q:'high', bg:'opaque', p:`epic title splash: a glowing luminous pen morphing into a sword blade held aloft, before a colossal dark rune tower, three guardian sigils orbiting the tower (cyan sigma, violet omega, crimson delta), ${PAINT}, dark negative space at top third for logo, deep blue darkness dominates, cinematic scale`},
  {f:'bg-gate1.jpg', s:'1536x1024', q:'high', bg:'opaque', p:`vast underground rune cavern arena, glowing cyan glyph pillars, mist floor reflection, wide empty center stage, ${PAINT}, deep blue darkness dominates 70 percent, cinematic wide shot`},
 {f:'bg-gate2.jpg', s:'1536x1024', q:'high', bg:'opaque', p:`twisted shadow forest arena at night, violet witchlights between tall black trees, wide empty center stage, ${PAINT}, darkness dominates 70 percent, cinematic wide shot`},
 {f:'bg-gate3.jpg', s:'1536x1024', q:'high', bg:'opaque', p:`open-air tower summit arena above clouds, crimson storm sky, burning rune ring on floor, wide empty center stage, ${PAINT}, darkness dominates 70 percent, cinematic wide shot`},
 {f:'ui-console.png',  s:'1536x1024', q:'high',   bg:'transparent', p:`ornate rectangular frame border for a quiz console panel, ${FRAME}, completely empty transparent center for nine-slice scaling, gold corner accents`},
 {f:'ui-bossbar.png',  s:'1536x1024', q:'high',   bg:'transparent', p:`long horizontal health bar housing frame, segmented ticks, engraved end caps, ${FRAME}, empty transparent inner channel`},
 {f:'ui-hpbar.png',    s:'1536x1024', q:'medium', bg:'transparent', p:`compact horizontal player health bar frame, small green gem end caps, ${FRAME}, empty transparent inner channel`},
 {f:'ui-tile-light.png',s:'1024x1024',q:'medium', bg:'transparent', p:`square ability button socket with cyan crystal inlay ring, ${ENAMEL}`},
 {f:'ui-tile-heavy.png',s:'1024x1024',q:'medium', bg:'transparent', p:`square ability button socket with amber ember crystal inlay ring, ${ENAMEL}`},
 {f:'ui-gem-off.png',  s:'1024x1024', q:'medium', bg:'transparent', p:`rhombus diamond-shaped gem socket, dark unlit smoky glass, ${ENAMEL}`},
 {f:'ui-gem-lit.png',  s:'1024x1024', q:'medium', bg:'transparent', p:`rhombus diamond-shaped gem, glowing violet enamel, radiant inner light, ${ENAMEL}`},
 {f:'ui-badge-silver.png',s:'1024x1024',q:'medium',bg:'transparent',p:`round rarity emblem, brushed silver enamel laurel, ${ENAMEL}`},
 {f:'ui-badge-gold.png',  s:'1024x1024',q:'medium',bg:'transparent',p:`round rarity emblem, engraved radiant gold enamel laurel, ${ENAMEL}`},
 {f:'ui-badge-prism.png', s:'1024x1024',q:'medium',bg:'transparent',p:`round rarity emblem, iridescent prismatic opal enamel laurel, ${ENAMEL}`},
 {f:'ui-cardbg-silver.png',s:'1024x1536',q:'high', bg:'opaque', p:`vertical trading card background, dark slate parchment with subtle silver filigree border, ${PAINT}, empty center for card content`},
 {f:'ui-cardbg-gold.png',  s:'1024x1536',q:'high', bg:'opaque', p:`vertical trading card background, dark parchment with ornate gold filigree border, ${PAINT}, empty center for card content`},
 {f:'ui-cardbg-prism.png', s:'1024x1536',q:'high', bg:'opaque', p:`vertical trading card background, dark parchment with iridescent prismatic filigree border, ${PAINT}, empty center for card content`},
 {f:'ui-drafttable.jpg',   s:'1536x1024',q:'high', bg:'opaque', p:`dark arcane cloth table backdrop viewed from above, faint woven rune patterns, candle-warm vignette at edges, ${PAINT}`},
];

const only = process.argv.includes('--only') ? process.argv[process.argv.indexOf('--only')+1] : null;
const force = process.argv.includes('--force');
const MODELS = ['gpt-image-2','gpt-image-1.5','gpt-image-1'];

async function gen(a){
  const fp = path.join(OUT, a.f);
  if(!force && fs.existsSync(fp)){ console.log('skip(已存在)', a.f); return; }
  for(const model of MODELS){
    const body = { model, prompt:a.p, size:a.s, quality:a.q, output_format:a.f.endsWith('jpg')?'jpeg':'png' };
    if(a.bg==='transparent') body.background='transparent';
    const r = await fetch('https://api.openai.com/v1/images/generations',{
      method:'POST', headers:{'Authorization':`Bearer ${KEY}`,'Content-Type':'application/json'},
      body: JSON.stringify(body)});
    const j = await r.json();
    if(j.data && j.data[0] && j.data[0].b64_json){
      fs.writeFileSync(fp, Buffer.from(j.data[0].b64_json,'base64'));
      console.log('OK', a.f, model, Math.round(fs.statSync(fp).size/1024)+'KB');
      return;
    }
    const msg = (j.error&&j.error.message)||'unknown';
    if(/model/i.test(msg) && MODELS.indexOf(model)<MODELS.length-1){ continue; }   // 模型不可用→降级
    console.log('FAIL', a.f, model, msg.slice(0,140));
    return;
  }
}
const list = ASSETS.filter(a=>!only || a.f.includes(only));
console.log('生成队列:', list.length, '张');
// 3 并发
let i=0;
async function worker(){ while(i<list.length){ const a=list[i++]; await gen(a); } }
await Promise.all([worker(),worker(),worker()]);
console.log('done');
